package entities2;
// Generated 9 dic 2024, 20:32:36 by Hibernate Tools 6.3.2.Final

import java.sql.Date;

/**
 * ProyectoSede generated by hbm2java
 */
public class ProyectoSede implements java.io.Serializable {

	private ProyectoSedeId id;
	private Sede sede;
	private Proyecto proyecto;
	private Date FInicio;
	private Date FFin;

	public ProyectoSede() {
	}

	public ProyectoSede(ProyectoSedeId id, Sede sede, Proyecto proyecto, Date FInicio) {
		this.id = id;
		this.sede = sede;
		this.proyecto = proyecto;
		this.FInicio = FInicio;
	}

	public ProyectoSede(ProyectoSedeId id, Sede sede, Proyecto proyecto, Date FInicio, Date FFin) {
		this.id = id;
		this.sede = sede;
		this.proyecto = proyecto;
		this.FInicio = FInicio;
		this.FFin = FFin;
	}

	public ProyectoSedeId getId() {
		return this.id;
	}

	public void setId(ProyectoSedeId id) {
		this.id = id;
	}

	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Date getFInicio() {
		return this.FInicio;
	}

	public void setFInicio(Date FInicio) {
		this.FInicio = FInicio;
	}

	public Date getFFin() {
		return this.FFin;
	}

	public void setFFin(Date FFin) {
		this.FFin = FFin;
	}

}
