package entities2;
// Generated 9 dic 2024, 20:32:36 by Hibernate Tools 6.3.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Sede generated by hbm2java
 */
public class Sede implements java.io.Serializable {

	private Integer idSede;
	private String nomSede;
	private Set departamentos = new HashSet(0);
	private Set proyectoSedes = new HashSet(0);

	public Sede() {
	}

	public Sede(String nomSede) {
		this.nomSede = nomSede;
	}

	public Sede(String nomSede, Set departamentos, Set proyectoSedes) {
		this.nomSede = nomSede;
		this.departamentos = departamentos;
		this.proyectoSedes = proyectoSedes;
	}

	public Integer getIdSede() {
		return this.idSede;
	}

	public void setIdSede(Integer idSede) {
		this.idSede = idSede;
	}

	public String getNomSede() {
		return this.nomSede;
	}

	public void setNomSede(String nomSede) {
		this.nomSede = nomSede;
	}

	public Set getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set departamentos) {
		this.departamentos = departamentos;
	}

	public Set getProyectoSedes() {
		return this.proyectoSedes;
	}

	public void setProyectoSedes(Set proyectoSedes) {
		this.proyectoSedes = proyectoSedes;
	}

}
