package ejercicioNavidad_clases;
// Generated 8 ene 2025, 1:26:36 by Hibernate Tools 6.5.1.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Departments generated by hbm2java
 */

@Entity
@Table(name = "departments")
public class Departments implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "dept_no", nullable = false, length = 4)
	private String dept_no;
	
	@Column(name = "dept_name", nullable = false, length = 40)
	private String deptName;
	
	public Departments() {
	}

	public Departments(String deptNo, String deptName) {
		this.dept_no = deptNo;
		this.deptName = deptName;
	}

	public String getDept_no() {
		return dept_no;
	}

	public void setDept_no(String dept_no) {
		this.dept_no = dept_no;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	
}
