package ejercicioNavidad_clases;
// Generated 8 ene 2025, 1:26:36 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MapsId;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * DeptEmp generated by hbm2java
 */
@Entity
@Table(name = "dept_emp")
public class DeptEmp implements java.io.Serializable {

	public DeptEmp(DeptEmpId id, Employees empleado, Departments departamento, Date fromDate, Date toDate) {
		super();
		this.id = id;
		this.empleado = empleado;
		this.departamento = departamento;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}

	@EmbeddedId
	private DeptEmpId id = new DeptEmpId();
	
	@ManyToOne
	@MapsId("variableEmpleado")
	@JoinColumn(name = "emp_no")
	private Employees empleado;
	
	@OneToOne
	@MapsId("variableDepartamento")
	@JoinColumn(name = "dept_no")
	private Departments departamento;
	
	
	@Column(name = "from_date", nullable = true, length = 10)
	private Date fromDate;
	
	@Column(name = "to_date", nullable = true, length = 10)
	private Date toDate;

	public DeptEmp() {
	}
	
	public DeptEmpId getId() {
		return id;
	}

	public void setId(DeptEmpId id) {
		this.id = id;
	}

	public Employees getEmpleado() {
		return empleado;
	}

	public void setEmpleado(Employees empleado) {
		this.empleado = empleado;
	}

	public Departments getDepartamento() {
		return departamento;
	}

	public void setDepartamento(Departments departamento) {
		this.departamento = departamento;
	}

	public Date getFromDate() {
		return fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

}
