package ejercicioNavidad_clases;
// Generated 8 ene 2025, 1:26:36 by Hibernate Tools 6.5.1.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * DeptEmpId generated by hbm2java
 */
@Embeddable
public class DeptEmpId implements java.io.Serializable {

	private String variableDepartamento;
	private int variableEmpleado;

	public DeptEmpId() {
	}

	public DeptEmpId(String deptNo, int empNo) {
		this.variableDepartamento = deptNo;
		this.variableEmpleado = empNo;
	}

	public String getDeptNo() {
		return this.variableDepartamento;
	}

	public void setDeptNo(String deptNo) {
		this.variableDepartamento = deptNo;
	}

	public int getEmpNo() {
		return this.variableEmpleado;
	}

	public void setEmpNo(int empNo) {
		this.variableEmpleado = empNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeptEmpId))
			return false;
		DeptEmpId castOther = (DeptEmpId) other;

		return ((this.getDeptNo() == castOther.getDeptNo()) || (this.getDeptNo() != null
				&& castOther.getDeptNo() != null && this.getDeptNo().equals(castOther.getDeptNo())))
				&& (this.getEmpNo() == castOther.getEmpNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeptNo() == null ? 0 : this.getDeptNo().hashCode());
		result = 37 * result + this.getEmpNo();
		return result;
	}

	public String getVariable_departamento() {
		return variableDepartamento;
	}

	public void setVariable_departamento(String variable_departamento) {
		this.variableDepartamento = variable_departamento;
	}

	public int getVariable_empleado() {
		return variableEmpleado;
	}

	public void setVariable_empleado(int variable_empleado) {
		this.variableEmpleado = variable_empleado;
	}
	
	

}
