package ejercicioNavidad_clases;
// Generated 8 ene 2025, 1:26:36 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import entities.EmpleadoDatosProf;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "employees")
public class Employees implements java.io.Serializable {

	public Employees(int emp_no, Date birthDate, String firstName, String lastName, char gender, Date hireDate,
			Set<Salaries> salarios, Titles titulo) {
		super();
		this.emp_no = emp_no;
		this.birthDate = birthDate;
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
		this.hireDate = hireDate;
		this.salarios = salarios;
		this.titulo = titulo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "emp_no", nullable = false, length = 4)
	private int emp_no;
	
	@Column(name = "birth_date", nullable = true, length = 10)
	private Date birthDate;
	
	@Column(name = "first_name", nullable = false, length = 14)
	private String firstName;
	
	@Column(name = "last_name", nullable = false, length = 16)
	private String lastName;
	
	@Column(name = "gender", nullable = false, length = 1)
	private char gender;
	
	@Column(name = "hire_date", nullable = true, length = 10)
	private Date hireDate;
	
	@OneToMany(mappedBy = "empleado", cascade = CascadeType.ALL)
	private Set<Salaries> salarios;
	
	@OneToOne(mappedBy = "empleado", cascade = CascadeType.ALL)
	private Titles titulo;

	public Employees() {
	}

	public int getEmp_no() {
		return emp_no;
	}

	public void setEmp_no(int emp_no) {
		this.emp_no = emp_no;
	}

	public Date getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public char getGender() {
		return gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	public Date getHireDate() {
		return hireDate;
	}

	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	public Set<Salaries> getSalarios() {
		return salarios;
	}

	public void setSalarios(Set<Salaries> salarios) {
		this.salarios = salarios;
	}

	public Titles getTitulo() {
		return titulo;
	}

	public void setTitulo(Titles titulo) {
		this.titulo = titulo;
	}

	

}
