package ejercicioNavidad_clases;
// Generated 8 ene 2025, 1:26:36 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MapsId;
import jakarta.persistence.Table;

/**
 * Salaries generated by hbm2java
 */
@Entity
@Table(name = "salaries")
public class Salaries implements java.io.Serializable {

	public Salaries(SalariesId id, Employees empleado, int salary, Date toDate) {
		super();
		this.id = id;
		this.empleado = empleado;
		this.salary = salary;
		this.toDate = toDate;
	}

	@EmbeddedId
	SalariesId id = new SalariesId();
	
	@ManyToOne
	@MapsId("emp_no")
	@JoinColumn(name = "emp_no")
	private Employees empleado;
	
	@Column(name = "salary", nullable = false)
	private int salary;
	
	@Column(name = "to_date", nullable = true, length = 10)
	private Date toDate;
	
	public Salaries() {
	}

	public SalariesId getId() {
		return id;
	}

	public void setId(SalariesId id) {
		this.id = id;
	}

	public Employees getEmpleado() {
		return empleado;
	}

	public void setEmpleado(Employees empleado) {
		this.empleado = empleado;
	}

	public int getSalary() {
		return salary;
	}

	public void setSalary(int salary) {
		this.salary = salary;
	}

	public Date getToDate() {
		return toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	
	
	
	

	
}
