package ejercicioNavidad_clases;
// Generated 8 ene 2025, 1:26:36 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * SalariesId generated by hbm2java
 */
@Embeddable
public class SalariesId implements java.io.Serializable {

	private int emp_no;
	
	@Column(name = "from_date", nullable = false)
	private Date fromDate;

	public SalariesId() {
	}

	public SalariesId(int empNo, Date fromDate) {
		this.emp_no = empNo;
		this.fromDate = fromDate;
	}

	public int getEmpNo() {
		return this.emp_no;
	}

	public void setEmpNo(int empNo) {
		this.emp_no = empNo;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalariesId))
			return false;
		SalariesId castOther = (SalariesId) other;

		return (this.getEmpNo() == castOther.getEmpNo())
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEmpNo();
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
