package ejercicioNavidad_clases;
// Generated 8 ene 2025, 1:26:36 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.MapsId;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * Titles generated by hbm2java
 */
@Entity
@Table(name = "titles")
public class Titles implements java.io.Serializable {

	@EmbeddedId
	private TitlesId id = new TitlesId();
	
	@OneToOne
	@MapsId("emp_no")
	@JoinColumn(name = "emp_no")
	private Employees empleado;
	
	@Column(name = "to_date", nullable = true, length = 10)
	private Date toDate;

	public Titles() {
	}

	public Titles(TitlesId id, Employees employees) {
		this.id = id;
		this.empleado = employees;
	}

	public Titles(TitlesId id, Employees employees, Date toDate) {
		this.id = id;
		this.empleado = employees;
		this.toDate = toDate;
	}

	public TitlesId getId() {
		return this.id;
	}

	public void setId(TitlesId id) {
		this.id = id;
	}

	public Employees getEmployees() {
		return this.empleado;
	}

	public void setEmployees(Employees employees) {
		this.empleado = employees;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

}
