package entities;
// Generated 12 dic 2024, 19:29:33 by Hibernate Tools 6.3.2.Final

/**
 * DepartamentoProyectosId generated by hbm2java
 */
public class DepartamentoProyectos implements java.io.Serializable {

	private int idDepto;
	private int idProy;

	public DepartamentoProyectos() {
	}

	public DepartamentoProyectos(int idDepto, int idProy) {
		this.idDepto = idDepto;
		this.idProy = idProy;
	}

	public int getIdDepto() {
		return this.idDepto;
	}

	public void setIdDepto(int idDepto) {
		this.idDepto = idDepto;
	}

	public int getIdProy() {
		return this.idProy;
	}

	public void setIdProy(int idProy) {
		this.idProy = idProy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DepartamentoProyectos))
			return false;
		DepartamentoProyectos castOther = (DepartamentoProyectos) other;

		return (this.getIdDepto() == castOther.getIdDepto()) && (this.getIdProy() == castOther.getIdProy());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDepto();
		result = 37 * result + this.getIdProy();
		return result;
	}

}
